name: AuthGui
version: ${project.version}
main: com.example.authgui.AuthGuiPlugin
api-version: 1.21
depend: [AuthMe]
softdepend: [floodgate]
commands:
  openlogin:
    description: 手动打开登录界面
    permission: authgui.use


